### ISSUE TITLE
我有个困惑

### ISSUE THREAD

**Issue by beforeuwait** [rockswang/wsjs.saic.mmewmd#2]
我自己通过console调试出来的 FSSBBIl1UgzbN7N80T 比实际的FSSBBIl1UgzbN7N80T 要少十几位，是因为他的 listener监听到了我在调试，然后修改了某些参数？

**Comment by rockswang** [comment]
可能是运行时机问题，F80T会刷新好几次，刚开始没有收集客户端事件，产生的值就短，页面运行一段时间后，监听到了客户端事件，产生的数据就长一些

**Comment by beforeuwait** [comment]
对，这个我验证过，我在输出 f80t那里放了个 alert，从每次弹出来的值来看确实是算出来的值会越来越长。
