### ISSUE TITLE
请教关于瑞数的问题

### ISSUE THREAD

**Issue by idlefire** [rockswang/wsjs.saic.mmewmd#3]
请问在分析瑞数案例的时候，有没有出现过202响应码返回的情况

**Comment by javaswing** [comment]
> 请问在分析瑞数案例的时候，有没有出现过202响应码返回的情况

这个是最新版本的，会首页返回202，但是返回的html有内容，执行了JS之后，会在本地存一些变量，然后再次请求就会返回200

**Comment by idlefire** [comment]
好的 多谢

**Comment by javaswing** [comment]
> 好的 多谢

有兴趣加个好友吗？我也在搞这个公司加密的接口。学习下

**Comment by idlefire** [comment]
可以啊 一起学习学习 
QQ
![image](https://user-images.githubusercontent.com/18007341/128041562-5e11a3b4-4871-4c9b-858b-98c5491fdf6e.png)
